// <auto-generated />
namespace OTS_ENTITIES.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class _954 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_954));
        
        string IMigrationMetadata.Id
        {
            get { return "201910301446277_954"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
